In [1]:
import pandas as pd

In [2]:
base = pd.read_csv('../API/MoviesPopular.csv')
print(base.columns)

Index(['Unnamed: 0', 'adult', 'backdrop_path', 'belongs_to_collection',
       'budget', 'genres', 'homepage', 'id', 'imdb_id', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'video', 'vote_average', 'vote_count'],
      dtype='object')

In [3]:
#Chargement des bases scrappées sur wikipédia pour nettoyage et fusion avec la base de données récupérée sur TMDB

#Academy award for best cinematography 
ac_bc = pd.read_csv('../wiki_scrap/academy_bc.csv')
# academy award for best film 
ac_bf = pd.read_csv('../wiki_scrap/academy_bf.csv')
#Academy award for best director 
ac_bd = pd.read_csv('../wiki_scrap/academy_bd.csv')
#Cannes Grand Prix
can_gp = pd.read_csv('../wiki_scrap/cannes_gp.csv')
#Cannes Jury prize
can_jr = pd.read_csv('../wiki_scrap/cannes_jury.csv')
#Cannes Palme d'or
can_po = pd.read_csv('../wiki_scrap/palme_or.csv')
#César Best director 
ces_bd = pd.read_csv('../wiki_scrap/cesar_bd.csv')
#Cesar Best Film 
ces_bf = pd.read_csv('../wiki_scrap/cesar_bf.csv')
#Venice Lion d'or
ven_lor = pd.read_csv('../wiki_scrap/lion_or.csv')
#Venice Lion d'argent 
ven_larg = pd.read_csv('../wiki_scrap/lion_argent.csv')
#Venice Grand Jury Prix
ven_gj = pd.read_csv('../wiki_scrap/venice_gj.csv')

In [4]:
#Pour vérifier si le chargement est bien réussi 

print(ac_bc.columns)
print(ac_bd.columns) 
print(ac_bf.columns) 

print(ces_bd.columns) 
print(ces_bf.columns) 

print(can_gp.columns)
print(can_jr.columns) 
print(can_po.columns)

print(ven_lor.columns) 
print(ven_larg.columns) 
print(ven_gj.columns)

Index(['Category', 'Name', 'Superlative', 'Year', 'Notes', 'Film', 'Nominees',
       'Awards', 'Nominations', 'Recipient'],
      dtype='object')
Index(['0', 'Year', 'Director(s)', 'Film', 'Ref.', 'Wins', 'Director',
       'Nominations', 'Record', 'Age'],
      dtype='object')
Index(['Year of Film Release', 'Film', 'Film Studio',
       'Film Studio/Producer(s)', 'Producer(s)', 'Production Company',
       'Nominations', 'Wins'],
      dtype='object')
Index(['Superlative', 'Men', 'Men.1', 'Women', 'Women.1', 'Year',
       'Winner and nominees', 'English title', 'Original title',
       'Winners and nominees', 'Wins', 'Director', 'Nominations'],
      dtype='object')
Index(['Year', 'English title', 'Original title', 'Director'], dtype='object')
Index(['('Year', '1960s', 'Awarded as "Grand Prix Spécial du Jury"')',
       '('English Title', '1960s', 'Awarded as "Grand Prix Spécial du Jury"')',
       '('Original Title', '1960s', 'Awarded as "Grand Prix Spécial du Jury"')',
       '('Director(s)', '1960s', 'Awarded as "Grand Prix Spécial du Jury"')',
       '('Production Country', '1960s', 'Awarded as "Grand Prix Spécial du Jury"')',
       'Number of Wins', 'Directors', 'Nationality', 'Films', 'Ref(s)'],
      dtype='object')
Index(['('Year', '1940s', 'Awarded as "International Jury Prize"')',
       '('English Title', '1940s', 'Awarded as "International Jury Prize"')',
       '('Original Title', '1940s', 'Awarded as "International Jury Prize"')',
       '('Recipient', '1940s', 'Awarded as "International Jury Prize"')',
       '('Production Country', '1940s', 'Awarded as "International Jury Prize"')',
       'Number of Wins', 'Directors', 'Nationality', 'Films'],
      dtype='object')
Index(['Year', 'English Title', 'Original title', 'Director(s)',
       'Production Country', 'Ref.', 'Original Title', 'Director', 'Ref(s)',
       'Recipient', 'Profession', 'Nationality of Recipient'],
      dtype='object')
Index(['('Year', '1940s')', '('English Title', '1940s')',
       '('Original Title', '1940s')', '('Director(s)', '1940s')',
       '('Production Country', '1940s')', 'Year', 'Winner(s)'],
      dtype='object')
Index(['('Year', '1990s')', '('Director(s)', '1990s')',
       '('English Title', '1990s')', '('Original Title', '1990s')',
       'Number of Wins', 'Director', 'Nationality', 'Films', 'Year',
       'English Title', 'Original Title', 'Director(s)', 'Production Country',
       'Screenwriter'],
      dtype='object')
Index(['('Year', '1950s', 'Awarded as "Special Jury Prize"')',
       '('English Title', '1950s', 'Awarded as "Special Jury Prize"')',
       '('Original Title', '1950s', 'Awarded as "Special Jury Prize"')',
       '('Director(s)', '1950s', 'Awarded as "Special Jury Prize"')',
       '('Production Country', '1950s', 'Awarded as "Special Jury Prize"')',
       'Number of Wins', 'Directors', 'Nationality'],
      dtype='object')

In [15]:
#Nettoyage et mise en conformité de la base de données Academy 

#Best-cinematography 

#Supprimer les 3 premières et 3 dernières colonnes et 13 premières lignes qui référent à un tableau qui ne nous intéresse pas dans notre code
ac_bc_cl = ac_bc.drop(['Category', 'Name', 'Superlative', 'Notes', 'Awards', 'Nominations', 'Recipient'], axis=1)

ac_bc_cl = ac_bc_cl.iloc[13:, :]
ac_bc_cl = ac_bc_cl.dropna(how='all')
ac_bc_cl['Year'] = ac_bc_cl['Year'].astype(str)

ac_bc_cl['Year'] = ac_bc_cl['Year'].str.extract('(\d{4})', expand=False)
ac_bc_cl['Year'] = pd.to_datetime(ac_bc_cl['Year'], format='%Y', errors='coerce')


ac_bc_cl

,Year,Film,Nominees
13,1927-01-01,Sunrise: A Song of Two Humans,Charles Rosher Karl Struss
14,1927-01-01,The Devil Dancer,George Barnes
15,1927-01-01,The Magic Flame,George Barnes
16,1927-01-01,Sadie Thompson,George Barnes
17,1928-01-01,NaN,NaN
...,...,...,...
782,2022-01-01,All Quiet on the Western Front,James Friend
783,2022-01-01,"Bardo, False Chronicle of a Handful of Truths",Darius Khondji
784,2022-01-01,Elvis,Mandy Walker
785,2022-01-01,Empire of Light,Roger Deakins
786,2022-01-01,Tár,Florian Hoffmeister

In [7]:
ac_bd_cl = ac_bd.drop (['0', 'Ref.', 'Wins', 'Director', 'Nominations', 'Record', 'Age' ], axis=1)
ac_bd_cl = ac_bd_cl.dropna(how='all')
ac_bd_cl = ac_bd_cl.iloc[:473, :]
ac_bd_cl.head(20)

,Year,Director(s),Film
1,1927/28 (1st),Frank Borzage (Dramatic Picture),7th Heaven
2,1927/28 (1st),Herbert Brenon (Dramatic Picture),Sorrell and Son
3,1927/28 (1st),King Vidor (Dramatic Picture),The Crowd
4,1927/28 (1st),Lewis Milestone (Comedy Picture),Two Arabian Knights
5,1927/28 (1st),Ted Wilde (Comedy Picture),Speedy
6,1927/28 (1st),Charlie Chaplin (Comedy Picture),The Circus[note 1]
7,1928/29 (2nd) [note 2],Frank Lloyd,The Divine Lady
8,1928/29 (2nd) [note 2],Lionel Barrymore,Madame X
9,1928/29 (2nd) [note 2],Harry Beaumont,The Broadway Melody
10,1928/29 (2nd) [note 2],Irving Cummings,In Old Arizona
11,1928/29 (2nd) [note 2],Frank Lloyd,Drag
12,1928/29 (2nd) [note 2],Frank Lloyd,Weary River
13,1928/29 (2nd) [note 2],Ernst Lubitsch,The Patriot
14,1929/30 (3rd),Lewis Milestone,All Quiet on the Western Front
15,1929/30 (3rd),Clarence Brown,Anna Christie
16,1929/30 (3rd),Clarence Brown,Romance
17,1929/30 (3rd),Robert Z. Leonard,The Divorcee
18,1929/30 (3rd),Ernst Lubitsch,The Love Parade
19,1929/30 (3rd),King Vidor,Hallelujah!
20,1930/31 (4th),Norman Taurog,Skippy